package ar.com.smg.carencias;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Afiliado implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String idAfiliado;

   public Afiliado()
   {
   }

   public java.lang.String getIdAfiliado()
   {
      return this.idAfiliado;
   }

   public void setIdAfiliado(java.lang.String idAfiliado)
   {
      this.idAfiliado = idAfiliado;
   }

   public Afiliado(java.lang.String idAfiliado)
   {
      this.idAfiliado = idAfiliado;
   }

}