package ar.com.smg.carencias;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Autorizacion implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Autorizacion() {
    }

}