package ar.com.smg.carencias;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Carencia implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Integer meses;
   private java.lang.Integer nomen;
   private java.lang.String plan;
   private java.lang.Integer prestac;

   public Carencia()
   {
   }

   public java.lang.Integer getMeses()
   {
      return this.meses;
   }

   public void setMeses(java.lang.Integer meses)
   {
      this.meses = meses;
   }

   public java.lang.Integer getNomen()
   {
      return this.nomen;
   }

   public void setNomen(java.lang.Integer nomen)
   {
      this.nomen = nomen;
   }

   public java.lang.String getPlan()
   {
      return this.plan;
   }

   public void setPlan(java.lang.String plan)
   {
      this.plan = plan;
   }

   public java.lang.Integer getPrestac()
   {
      return this.prestac;
   }

   public void setPrestac(java.lang.Integer prestac)
   {
      this.prestac = prestac;
   }

   public Carencia(java.lang.Integer meses, java.lang.Integer nomen,
         java.lang.String plan, java.lang.Integer prestac)
   {
      this.meses = meses;
      this.nomen = nomen;
      this.plan = plan;
      this.prestac = prestac;
   }

}